Fl 12492 back end front end favorite the course
Fielo-Apps/eLearning pull request #33
Opened 2022-07-29 14:35 UTC by FlaviFielo

2022-07-29 16:51 UTC, renamath approved these changes

2022-07-29 17:42 UTC, lpereirafielo requested changes

2022-07-29 17:42 UTC, lpereirafielo commented on force-app/main/default/classes/MembersSelector.cls
> +            throw new IllegalArgumentException('memberId cannot be null');
Flaviano as mensagem tem que ser por labels

2022-07-29 17:42 UTC, lpereirafielo commented on force-app/main/default/classes/MembersSelector.cls
> +            throw new IllegalArgumentException('memberId should be Member sobject');
Flaviano as mensagem tem que ser por labels

2022-07-29 17:42 UTC, lpereirafielo commented on force-app/main/default/classes/MembersService.cls
> +            throw new IllegalArgumentException('courseId cannot be null');
Flaviano as mensagem tem que ser por labels

2022-07-29 17:42 UTC, lpereirafielo commented on force-app/main/default/classes/MembersService.cls
> +            throw new IllegalArgumentException('courseId should be Course sobject');
Flaviano as mensagem tem que ser por labels

2022-07-29 17:42 UTC, lpereirafielo commented on force-app/main/default/classes/TestMembersSelector.cls
> +            FieloPLT__OnlineTransactionProcessing__c = true//,
// remover

2022-07-29 17:42 UTC, lpereirafielo commented on force-app/main/default/lwc/favoriteCourse/favoriteCourse.js
> +          title: "Attention",
Flaviano as mensagem tem que ser por labels

2022-07-29 17:42 UTC, lpereirafielo commented on force-app/main/default/lwc/favoriteCourse/favoriteCourse.js
> +          message: "it was not possible to {0} the course",
Flaviano as mensagem tem que ser por labels

2022-08-01 12:54 UTC, lpereirafielo approved these changes

2022-08-01 12:59 UTC, merged